### ISSUE TITLE
Links to episodes are missing on the website

### ISSUE THREAD

**Issue by bripkens** [autoweirdfm/autoweirdfm.github.io#2]
The website does not contain links to the mp3 files. One currently has to browse the RSS feed in order to extract this information.

**Comment by britter** [comment]
Hello @bripkens,

I'm planning to add something like [this](https://github.com/joebuhlig/joebuhlig_com/blob/master/_includes/podcast_player.html) to podcast announcements. Would that work for you?

**Comment by bripkens** [comment]
absolutely Mr. @britter :)
