### ISSUE TITLE
iTunes Support

### ISSUE THREAD

**Issue by joyheron** [autoweirdfm/autoweirdfm.github.io#3]
Is the podcast actually on iTunes yet? I searched for it today and couldn't find it (maybe a link for the website would be a good idea too).

**Comment by britter** [comment]
Hello @joyclark,

we submitted the podcast yesterday and we're waiting for the approval. I couldn't find any accurate data on how long the approval process takes, but I suspect that it will be available at iTunes very soon.

**Comment by holgergp** [comment]
Yes!! We're on iTunes! https://itunes.apple.com/de/podcast/autoweird.fm/id1180414602?mt=2
:)
