### ISSUE TITLE
Themenvorschlag: Sinn und Unsinn von Zertifikaten

### ISSUE THREAD

**Issue by MahatmaFatalError** [autoweirdfm/autoweirdfm.github.io#32]
Macht es aus eurer Sicht Sinn (persönlich oder finanziell), sich mit allerlei Zertifikaten zu schmücken oder ist das bloß Geldverschwendung.

Vielleicht sollte man hier differenzieren zwischen persönlichen (z.B. iSAQB, IREB, ISTQB, iBUQ, ISSECO, Oracle, ScrumAlliance etc.) und abteilungsweiten Zertifikaten (z.B. CMMI-DEV, ISO/IEC).

Wie ist da eure Erfahrung?

**Comment by kiview** [comment]
Ach, dachte geht um Sinn und Unsinn von SSL Zertifikaten :smirk_cat:

**Comment by MahatmaFatalError** [comment]
Thx!
