### ISSUE TITLE
PodLove Web Player

### ISSUE THREAD

**Issue by joschi** [autoweirdfm/autoweirdfm.github.io#47]
Es wäre super, wenn ihr einen Player wie den [Podlove Web Player](https://github.com/podlove/podlove-web-player) auf der Webseite verwenden könntet, der einige fortgeschrittene Features wie etwa Kapitelmarken und Steuerung der Abspielgeschwindigkeit unterstützt.

Das hilft dann auch den Leuten, denen ihr zu schnell oder zu langsam redet. 😉

**Comment by Riggs333** [comment]
Für die Steuerung der **Abspielgeschwindigkeit** von Audio- und Video-Elementen auf Webseiten kann ich die Chrome-Extension [HTML5 Video Speed Controller](https://github.com/igrigorik/videospeed) empfehlen.

Für Podcasts nutze ich allerdings - weil ich meist nur unterwegs höre - auf meinem Android-Smartphone [AntennaPod](https://github.com/AntennaPod/AntennaPod), mit dem sich auch die Geschwindigkeit regeln lässt.

**Comment by britter** [comment]
Hallo! Wie schon ein paar mal im Podcast angedeutet überlegen wir im Moment mit der ganzen Website auf eine andere Plattform zu wechseln. Es gibt ein paar Sachen, die uns an unserer GitHub Pages Lösung stören. Im Moment scheitert es allerdings zum Einen an der Zeit um das mal gescheit aufzusetzen und zum anderen an der Angst, dass wir den RSS Feed dadurch kaputt machen.

**Comment by MahatmaFatalError** [comment]
Was natürlich extrem genial wäre, wären durchsuchbare **Transkriptionen** https://docs.podlove.org/podlove-web-player/transcripts.html

**Comment by britter** [comment]
Unsere neue Website ist heute online gegangen und wir haben jetzt den Podlove Webplayer am Start!
