### ISSUE TITLE
Plauderlaune: Docker

### ISSUE THREAD

**Issue by SteKoe** [autoweirdfm/autoweirdfm.github.io#5]
Hallo ihr beiden,

ich habe gespannt eure ersten Podcasts verfolgt und würde gerne ebenfalls das Thema Docker aus eurer Sicht nochmal hören. Dabei interessieren mich natürlich exklusive Insights eures täglichen Lebens: 

 - Wo setzt ihr Docker ein? 
 - Auf welcher Platform nutzt ihr Docker? Windows, Linux, Mac OS?
 - Docker als "new level of abstraction": Egal welche Technologie eingesetzt wird, Docker bring eine homogenisierung mit sich - was denkt ihr?
 - Docker Swarm, oder Kubernetes? Was sind eure Erfahrungen?
 - Datenbanken in Docker, ein No-Go?
 - Eure persönliche Meinung von Docker: Ein Hype, der bald wieder verschwindet?

Viele Grüße
Stephan

**Comment by britter** [comment]
Hallo Stephan,

schön, dass dir der Podcast gefällt. Wir nehmen deinen Vorschlag in unsere Themenliste auf. Hatten ja in Folge 0 bereits gesagt, dass wir da noch mal drüber sprechen wollen.

VG

**Comment by kiview** [comment]
Zu dem Blog-Post den ihr erwähnt hattet wollte ich auch unbedingt noch diesen Blog-Post entgegnen 😄 
https://patrobinson.github.io/2016/11/05/docker-in-production/

**Comment by holgergp** [comment]
Sehr schöner Artikel. Kannte ich noch nicht. Danke!

**Comment by kiview** [comment]
Ach cool, da freu ich mich schon drauf :)
