### ISSUE TITLE
Technik: Tonqualität

### ISSUE THREAD

**Issue by ansgarschulte** [autoweirdfm/autoweirdfm.github.io#7]
Moin,
ich finde man könnte euere Tonqualität noch etwas verbessern. Der Holger hört sich so ein wenig zugeschaltet an. Als wenn er aus dem Off spricht. Anderes Mikro / Soundkarte?!

**Comment by britter** [comment]
Hi,

der @holgergp hat in Folge 4 mal ein anderes Mikrofon probiert. War es besser?

VG

**Comment by ansgarschulte** [comment]
Hi, 
ja, war mir sogar direkt aufgefallen 👍 🔝

VG
